<?php
//Wiki documentation setting
$nedashDocPath="/var/lib/neteye/dokuwiki/data/pages/neteye/nedashboard.txt";
$dashWikiURL="../../wiki/doku.php?id=neteye:nedashboard";
//NetEye paths
//Location of status.cgi
$statusURL="../../../neteye/cgi-bin/status.cgi";
//Dashboard layout setting
$DB_formwidth=730;
$DB_tachosInRow=5;
$DB_minutesToBeInactive=15;
$DB_diashowRefreshTime=15;
$DB_defaultBoard="availability1";
$DB_availability=80;
$DB_timeperiodHost="lastmonth";
$DB_timeperiodService="lastmonth";
$DB_availCGIUserPass="guest:guest";
?>
